---
name: Backport Assistant Runner

on:
  pull_request_target:
    types:
      - closed

permissions:
  contents: write # to push to a new branch
  pull-requests: write # to create a new PR

jobs:
  backport:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    container: hashicorpdev/backport-assistant:0.4.7@sha256:36f9d4fba82b9454f1f62bf76c8078fafe3ab0be71356cb96af6d56ac4482cd8
    steps:
      - name: Run Backport Assistant
        run: |
          backport-assistant backport
        env:
          BACKPORT_LABEL_REGEXP: "(?P<target>\\d+\\.\\d+)-backport"
          BACKPORT_TARGET_TEMPLATE: "v{{.target}}"
          BACKPORT_CREATE_DRAFT_ALWAYS: true
          GITHUB_TOKEN: ${{ github.token }}
