name: manual-equivalence-tests

on:
  workflow_dispatch:
    inputs:
      target-branch:
        type: string
        description: "Which branch should be updated?"
        required: true
      terraform-version:
        type: string
        description: "Terraform version to run against (no v prefix, eg. 1.4.4)."
        required: true
      equivalence-test-version:
        type: string
        description: 'Equivalence testing framework version to use (no v prefix, eg. 0.3.0).'
        default: "0.3.0"
        required: true

permissions:
  contents: write # We push updates to the equivalence tests back into the repository.

jobs:
  run-equivalence-tests:
    name: "Run equivalence tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          ref: ${{ inputs.target-branch }}
      - uses: ./.github/actions/equivalence-test
        with:
          target-terraform-version: ${{ inputs.terraform-version }}
          target-terraform-branch: ${{ inputs.target-branch }}
          target-equivalence-test-version: ${{ inputs.equivalence-test-version }}
          target-os: linux
          target-arch: amd64
